# Generated by Django 5.1.5 on 2025-02-17 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('damaged', 'Damaged')], max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipment_photos/')),
                ('is_being_used', models.BooleanField(default=False)),
                ('nothing_missing', models.BooleanField(default=True)),
                ('usages', models.JSONField(blank=True, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('is_for_kids', models.BooleanField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='locations.location')),
            ],
        ),
    ]
