# Generated by Django 5.1.5 on 2025-01-22 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('damaged', 'Damaged')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='equipment_photos/')),
                ('is_being_used', models.BooleanField(default=False)),
                ('nothing_missing', models.BooleanField(default=True)),
                ('usages', models.JSONField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='locations.location')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
            },
        ),
    ]
