# Generated by Django 5.1.6 on 2025-02-27 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('schools', '0001_initial'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='schools.school'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='equipments', to='sports.sport'),
        ),
    ]
