# Generated by Django 5.1.5 on 2025-05-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='state',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('damaged', 'Damaged'), ('missing', 'Missing')], max_length=50, null=True),
        ),
    ]
