# Generated by Django 5.1.5 on 2025-01-29 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_equipment_options_equipment_brand_and_more'),
        ('locations', '0004_remove_location_sports'),
        ('schools', '0013_rename_equipment_prices_school_extra_prices_and_more'),
        ('sports', '0002_sport_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='equipments', to='sports.sport'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='state',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('damaged', 'Damaged')], max_length=50, null=True),
        ),
    ]
