# Generated by Django 5.1.5 on 2025-01-24 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_activity_school_activitymodel_school_camp_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='events.activitymodel'),
        ),
    ]
