# Generated by Django 5.1.5 on 2025-01-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_activity_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='starting_time',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='birthdayparty',
            old_name='starting_time',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='camp',
            old_name='finishing_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='camp',
            old_name='starting_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='birthdayparty',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
