// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7zeDW-2AMg8aEoOHZmE63QIaH0V2QS-I',
    appId: '1:368273500882:web:3ede5bf7cb27a946f15b0b',
    messagingSenderId: '368273500882',
    projectId: 'mylessons-7b4ed',
    authDomain: 'mylessons-7b4ed.firebaseapp.com',
    storageBucket: 'mylessons-7b4ed.firebasestorage.app',
    measurementId: 'G-7XPJK2X34H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhZLl-1j99yImJd2HM-7pG9gP8sTbKxPU',
    appId: '1:368273500882:android:be6411a9765c0f93f15b0b',
    messagingSenderId: '368273500882',
    projectId: 'mylessons-7b4ed',
    storageBucket: 'mylessons-7b4ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARpXszWp2ZunONwZugrEqC7IXEZpY5_ms',
    appId: '1:368273500882:ios:709b94d918b5ef1ef15b0b',
    messagingSenderId: '368273500882',
    projectId: 'mylessons-7b4ed',
    storageBucket: 'mylessons-7b4ed.firebasestorage.app',
    iosBundleId: 'com.example.mylessonsFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARpXszWp2ZunONwZugrEqC7IXEZpY5_ms',
    appId: '1:368273500882:ios:709b94d918b5ef1ef15b0b',
    messagingSenderId: '368273500882',
    projectId: 'mylessons-7b4ed',
    storageBucket: 'mylessons-7b4ed.firebasestorage.app',
    iosBundleId: 'com.example.mylessonsFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7zeDW-2AMg8aEoOHZmE63QIaH0V2QS-I',
    appId: '1:368273500882:web:be4c51f326fa11b6f15b0b',
    messagingSenderId: '368273500882',
    projectId: 'mylessons-7b4ed',
    authDomain: 'mylessons-7b4ed.firebaseapp.com',
    storageBucket: 'mylessons-7b4ed.firebasestorage.app',
    measurementId: 'G-F6NGRWGVVL',
  );
}
