// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAR9cU07q-tShEAN8HHGcmp5L2l9tMIFQ',
    appId: '1:768650226651:web:d44c8896f55ea458ca55fe',
    messagingSenderId: '768650226651',
    projectId: 'my-lessons-460316',
    authDomain: 'my-lessons-460316.firebaseapp.com',
    storageBucket: 'my-lessons-460316.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDez5gsI0EW_iM0gzo-gh3LNcW1Ya9H_tY',
    appId: '1:768650226651:android:5e60ab479126b0f5ca55fe',
    messagingSenderId: '768650226651',
    projectId: 'my-lessons-460316',
    storageBucket: 'my-lessons-460316.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkUZf3vxnJ8lFsCxaZMjqjB_N6Oggp-nE',
    appId: '1:768650226651:ios:a5c9b31fd1bac3e6ca55fe',
    messagingSenderId: '768650226651',
    projectId: 'my-lessons-460316',
    storageBucket: 'my-lessons-460316.firebasestorage.app',
    iosBundleId: 'com.example.mylessonsFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARpXszWp2ZunONwZugrEqC7IXEZpY5_ms',
    appId: '1:368273500882:ios:709b94d918b5ef1ef15b0b',
    messagingSenderId: '368273500882',
    projectId: 'mylessons-7b4ed',
    storageBucket: 'mylessons-7b4ed.firebasestorage.app',
    iosClientId: '368273500882-813i1dn6kojsob4dmlbd3i26lgrsmh0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mylessonsFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7zeDW-2AMg8aEoOHZmE63QIaH0V2QS-I',
    appId: '1:368273500882:web:be4c51f326fa11b6f15b0b',
    messagingSenderId: '368273500882',
    projectId: 'mylessons-7b4ed',
    authDomain: 'mylessons-7b4ed.firebaseapp.com',
    storageBucket: 'mylessons-7b4ed.firebasestorage.app',
    measurementId: 'G-F6NGRWGVVL',
  );

}