version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    # load your backend .env so django-environ works:
    env_file:
      - ./mylessons_backend/.env
    # mount your code, media & static for live edits:
    volumes:
      - ./mylessons_backend:/workspace/mylessons_backend:cached
      - ./mylessons_frontend:/workspace/mylessons_frontend:cached
      - ./mylessons_backend/media:/workspace/mylessons_backend/media
      - ./mylessons_backend/static:/workspace/mylessons_backend/static
      - ./mylessons_backend/staticfiles:/workspace/mylessons_backend/staticfiles
    ports:
      - "8000:8000"
    command: >
      sh -c "cd /workspace/mylessons_backend &&
             python manage.py migrate --no-input &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dbname
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
