# Generated by Django 5.1.6 on 2025-02-27 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0002_initial'),
        ('progress', '0001_initial'),
        ('sports', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='users.student'),
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='users.student'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='users.student'),
        ),
        migrations.AddField(
            model_name='skill',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='sports.sport'),
        ),
        migrations.AddField(
            model_name='goal',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='progress.skill'),
        ),
        migrations.AddField(
            model_name='skillproficiency',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proficiencies', to='progress.skill'),
        ),
        migrations.AddField(
            model_name='skillproficiency',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_proficiencies', to='users.student'),
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='progress_records', to='progress.skillproficiency'),
        ),
    ]
