# Generated by Django 5.1.5 on 2025-02-20 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_groupclass_instructors_and_more'),
        ('progress', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressrecord',
            name='group_class',
        ),
        migrations.AlterField(
            model_name='progressrecord',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='lessons.lesson'),
        ),
    ]
