# Generated by Django 5.1.5 on 2025-03-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressrecord',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='start_date',
        ),
        migrations.AddField(
            model_name='goal',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='goal',
            name='start_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='goals',
            field=models.ManyToManyField(blank=True, related_name='progress_records', to='progress.goal'),
        ),
        migrations.DeleteModel(
            name='SkillProficiency',
        ),
    ]
