# Generated by Django 5.1.5 on 2025-01-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_alter_skill_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressrecord',
            name='covered_skills',
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='progress_records', to='progress.skillproficiency'),
        ),
        migrations.DeleteModel(
            name='InstructorFeedback',
        ),
    ]
