# Generated by Django 5.1.5 on 2025-01-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_remove_progressrecord_covered_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
