# Generated by Django 5.1.5 on 2025-01-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='sports',
            field=models.ManyToManyField(related_name='locations', to='sports.sport'),
        ),
    ]
