# Generated by Django 5.1.5 on 2025-01-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_sports'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='locations', to='sports.sport'),
        ),
    ]
