# Generated by Django 5.1.5 on 2025-02-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_remove_location_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
