# Generated by Django 5.1.5 on 2025-01-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_lessons_pack_prices', models.JSONField()),
                ('group_lessons_pack_prices', models.JSONField()),
                ('name', models.CharField(max_length=255)),
                ('instructor_payments', models.JSONField()),
                ('equipment_prices', models.JSONField()),
                ('extras_prices', models.JSONField()),
                ('logo', models.ImageField(upload_to='school_logos/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
