# Generated by Django 5.1.5 on 2025-01-22 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('events', '0002_initial'),
        ('lessons', '0002_initial'),
        ('payments', '0002_initial'),
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.useraccount'),
        ),
        migrations.AddField(
            model_name='school',
            name='activities',
            field=models.ManyToManyField(related_name='schools', to='events.activity'),
        ),
        migrations.AddField(
            model_name='school',
            name='activity_models',
            field=models.ManyToManyField(related_name='schools', to='events.activitymodel'),
        ),
        migrations.AddField(
            model_name='school',
            name='camp_orders',
            field=models.ManyToManyField(related_name='schools', to='events.camporder'),
        ),
        migrations.AddField(
            model_name='school',
            name='camps',
            field=models.ManyToManyField(related_name='schools', to='events.camp'),
        ),
        migrations.AddField(
            model_name='school',
            name='class_tickets',
            field=models.ManyToManyField(related_name='schools', to='lessons.classticket'),
        ),
        migrations.AddField(
            model_name='school',
            name='discounts',
            field=models.ManyToManyField(related_name='schools', to='users.discount'),
        ),
        migrations.AddField(
            model_name='school',
            name='equipments',
            field=models.ManyToManyField(related_name='schools', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='school',
            name='group_classes',
            field=models.ManyToManyField(related_name='schools', to='lessons.groupclass'),
        ),
        migrations.AddField(
            model_name='school',
            name='group_packs',
            field=models.ManyToManyField(related_name='schools', to='lessons.grouppack'),
        ),
        migrations.AddField(
            model_name='school',
            name='instructors',
            field=models.ManyToManyField(related_name='schools', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='school',
            name='monitors',
            field=models.ManyToManyField(related_name='schools', to='users.monitor'),
        ),
        migrations.AddField(
            model_name='school',
            name='parents',
            field=models.ManyToManyField(related_name='schools', to='users.useraccount'),
        ),
        migrations.AddField(
            model_name='school',
            name='payments',
            field=models.ManyToManyField(related_name='schools', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='school',
            name='private_classes',
            field=models.ManyToManyField(related_name='schools', to='lessons.privateclass'),
        ),
        migrations.AddField(
            model_name='school',
            name='private_packs',
            field=models.ManyToManyField(related_name='schools', to='lessons.privatepack'),
        ),
        migrations.AddField(
            model_name='school',
            name='reviews',
            field=models.ManyToManyField(related_name='schools', to='schools.review'),
        ),
        migrations.AddField(
            model_name='school',
            name='student_groups',
            field=models.ManyToManyField(related_name='schools', to='users.studentgroup'),
        ),
        migrations.AddField(
            model_name='school',
            name='students',
            field=models.ManyToManyField(related_name='schools', to='users.student'),
        ),
        migrations.AddField(
            model_name='school',
            name='unavailabilities',
            field=models.ManyToManyField(related_name='schools', to='users.unavailability'),
        ),
        migrations.AddField(
            model_name='school',
            name='vouchers',
            field=models.ManyToManyField(related_name='schools', to='lessons.voucher'),
        ),
    ]
