# Generated by Django 5.1.5 on 2025-01-22 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='instructor_payments',
            new_name='payment_types',
        ),
        migrations.RemoveField(
            model_name='school',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='school',
            name='activity_models',
        ),
        migrations.RemoveField(
            model_name='school',
            name='camp_orders',
        ),
        migrations.RemoveField(
            model_name='school',
            name='camps',
        ),
        migrations.RemoveField(
            model_name='school',
            name='class_tickets',
        ),
        migrations.RemoveField(
            model_name='school',
            name='discounts',
        ),
        migrations.RemoveField(
            model_name='school',
            name='equipments',
        ),
        migrations.RemoveField(
            model_name='school',
            name='group_classes',
        ),
        migrations.RemoveField(
            model_name='school',
            name='group_packs',
        ),
        migrations.RemoveField(
            model_name='school',
            name='payments',
        ),
        migrations.RemoveField(
            model_name='school',
            name='private_classes',
        ),
        migrations.RemoveField(
            model_name='school',
            name='private_packs',
        ),
        migrations.RemoveField(
            model_name='school',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='school',
            name='student_groups',
        ),
        migrations.RemoveField(
            model_name='school',
            name='unavailabilities',
        ),
        migrations.RemoveField(
            model_name='school',
            name='vouchers',
        ),
        migrations.AddField(
            model_name='review',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='schools.school'),
        ),
        migrations.AddField(
            model_name='school',
            name='locations',
            field=models.ManyToManyField(related_name='schools', to='locations.location'),
        ),
    ]
