# Generated by Django 5.1.5 on 2025-01-23 11:45

import schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_rename_instructor_payments_school_payment_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='group_lessons_pack_prices',
            field=models.JSONField(default=schools.models.default_group_lessons_pack_prices),
        ),
        migrations.AlterField(
            model_name='school',
            name='private_lessons_pack_prices',
            field=models.JSONField(default=schools.models.default_private_lessons_pack_prices),
        ),
    ]
