# Generated by Django 5.1.5 on 2025-01-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_school_equipment_prices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='attendance_by_date',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
