# Generated by Django 5.1.5 on 2025-01-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_school_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='currency',
            field=models.CharField(default='EUR', max_length=20),
        ),
    ]
