# Generated by Django 5.1.5 on 2025-01-26 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_school_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='school_admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
