# Generated by Django 5.1.5 on 2025-01-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_school_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='notification_templates',
            field=models.JSONField(default=dict, help_text='Customizable templates for notifications.'),
        ),
    ]
