# Generated by Django 5.1.5 on 2025-01-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_school_schedule_time_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='equipment_prices',
            new_name='extra_prices',
        ),
        migrations.RemoveField(
            model_name='school',
            name='extras_prices',
        ),
    ]
