# Generated by Django 5.1.5 on 2025-01-29 19:51

import schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_rename_equipment_prices_school_extra_prices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='alerts',
            field=models.JSONField(blank=True, default=schools.models.default_alerts),
        ),
    ]
