# Generated by Django 5.1.5 on 2025-01-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='sports', to='sports.sport'),
        ),
    ]
