# Generated by Django 5.1.5 on 2025-01-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_school'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='equipment', to='sports.sport'),
        ),
    ]
