# Generated by Django 5.1.5 on 2025-01-22 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='schools.school'),
        ),
    ]
