# Generated by Django 5.1.5 on 2025-01-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_starting_time_activity_start_time_and_more'),
        ('lessons', '0016_privateclass_number_of_extra_students_and_more'),
        ('payments', '0003_payment_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='birthday_party',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='camp',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='group_pack',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='private_pack',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='voucher',
        ),
        migrations.AddField(
            model_name='payment',
            name='birthday_party',
            field=models.ManyToManyField(blank=True, related_name='payments', to='events.birthdayparty'),
        ),
        migrations.AddField(
            model_name='payment',
            name='camp',
            field=models.ManyToManyField(blank=True, related_name='payments', to='events.camporder'),
        ),
        migrations.AddField(
            model_name='payment',
            name='group_pack',
            field=models.ManyToManyField(blank=True, related_name='payments', to='lessons.grouppack'),
        ),
        migrations.AddField(
            model_name='payment',
            name='private_pack',
            field=models.ManyToManyField(blank=True, related_name='payments', to='lessons.privatepack'),
        ),
        migrations.AddField(
            model_name='payment',
            name='voucher',
            field=models.ManyToManyField(blank=True, related_name='payments', to='lessons.voucher'),
        ),
    ]
