name: mylessons_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  country_picker: ^2.0.15
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4
  http: ^1.3.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  table_calendar: ^3.2.0
  syncfusion_flutter_datepicker: ^28.2.7
  currency_picker: ^2.0.21
  provider: ^6.1.2
  url_launcher: ^6.3.1
  app_links: ^6.4.0
  flutter_stripe: ^11.4.0
  flutter_stripe_web: ^6.5.0
  connectivity_plus: 5.0.2
  intl_phone_field: ^3.2.0
  image_picker: ^1.1.2
  firebase_messaging: ^15.2.5
  file_picker: ^10.1.9
  permission_handler: ^12.0.0+1
  share_plus: ^11.0.0
  flutter_markdown: ^0.6.10


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_foreground: "assets/app_icon.png" # For Android adaptive icon
  adaptive_icon_background: "#ffffff" # Change background color if needed

flutter:
  assets:
    - assets/
    - assets/terms.md
    - assets/privacy.md
  uses-material-design: true
