# Generated by Django 5.1.5 on 2025-02-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.JSONField()),
                ('birthday_party', models.ManyToManyField(blank=True, related_name='payments', to='events.birthdayparty')),
                ('camp', models.ManyToManyField(blank=True, related_name='payments', to='events.camporder')),
                ('group_pack', models.ManyToManyField(blank=True, related_name='payments', to='lessons.grouppack')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
