# Generated by Django 5.1.5 on 2025-03-10 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0002_initial'),
        ('payments', '0001_initial'),
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='payment',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='payments', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='payment',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.monitor'),
        ),
        migrations.AddField(
            model_name='payment',
            name='packs',
            field=models.ManyToManyField(blank=True, related_name='payments', to='lessons.pack'),
        ),
        migrations.AddField(
            model_name='payment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='schools.school'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='vouchers',
            field=models.ManyToManyField(blank=True, related_name='payments', to='lessons.voucher'),
        ),
    ]
