# Generated by Django 5.1.5 on 2025-02-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_activity_price_alter_activity_monitor_price_and_more'),
        ('lessons', '0003_remove_groupclass_instructors_and_more'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='birthday_party',
            new_name='birthday_parties',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='camp',
            new_name='camp_orders',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='voucher',
            new_name='vouchers',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='group_pack',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='private_pack',
        ),
        migrations.AddField(
            model_name='payment',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='payments', to='events.activity'),
        ),
        migrations.AddField(
            model_name='payment',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='payments', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='payment',
            name='packs',
            field=models.ManyToManyField(blank=True, related_name='payments', to='lessons.pack'),
        ),
    ]
