# Generated by Django 5.1.6 on 2025-02-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='sports_photos/')),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
                ('locations', models.ManyToManyField(blank=True, related_name='sports', to='sports.sport')),
            ],
        ),
    ]
