# Generated by Django 5.1.6 on 2025-02-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='sports_photos/'),
        ),
    ]
