# Generated by Django 5.1.6 on 2025-02-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_address'),
        ('sports', '0002_alter_sport_benefits_alter_sport_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='sports', to='locations.location'),
        ),
    ]
