# Generated by Django 5.1.5 on 2025-03-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='payment_types',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
