# Generated by Django 5.1.5 on 2025-02-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='payments_by_school',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
