# Generated by Django 5.1.5 on 2025-04-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
        ('users', '0002_alter_useraccount_payment_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='sports.sport'),
        ),
    ]
