# Generated by Django 5.1.5 on 2025-02-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_instructor_payments_by_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='payments_by_school',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='balance_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
