# Generated by Django 5.1.5 on 2025-01-22 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_rename_instructor_payments_school_payment_types_and_more'),
        ('users', '0002_unavailability_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='schools.school'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='schools.school'),
        ),
        migrations.AddField(
            model_name='unavailability',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='schools.school'),
        ),
    ]
