# Generated by Django 5.1.5 on 2025-04-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0003_instructor_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='locations.location'),
        ),
    ]
