# Generated by Django 5.1.5 on 2025-02-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_instructor_payments_by_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='payment_types',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
