# Generated by Django 5.1.5 on 2025-02-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useraccount_payment_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='current_school_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
