# Generated by Django 5.1.5 on 2025-02-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_studentgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='current_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
