# Generated by Django 5.1.5 on 2025-02-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_useraccount_current_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='current_role',
            field=models.CharField(default='Parent', max_length=255),
        ),
    ]
