# Generated by Django 5.1.5 on 2025-05-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usercredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='calendar_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
