# Generated by Django 5.1.5 on 2025-05-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_useraccount_calendar_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
