# Generated by Django 5.1.5 on 2025-06-20 19:03

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_student_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('students', models.ManyToManyField(related_name='pairing_requests', to='users.student')),
            ],
        ),
    ]
