# Generated by Django 5.1.5 on 2025-06-24 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_pairingrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, help_text='One-time pairing key', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_keys', to='users.student')),
            ],
        ),
        migrations.DeleteModel(
            name='PairingRequest',
        ),
        migrations.AddIndex(
            model_name='associationkey',
            index=models.Index(fields=['key'], name='users_assoc_key_bef64a_idx'),
        ),
    ]
