# Generated by Django 5.1.5 on 2025-01-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unavailability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
