# Generated by Django 5.1.5 on 2025-01-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_student_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentGroup',
        ),
    ]
