# Generated by Django 5.1.5 on 2025-01-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_location_sports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='sports',
        ),
    ]
