# Generated by Django 5.1.5 on 2025-03-10 11:56

import schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_prices', models.JSONField(blank=True, default=dict)),
                ('services', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(max_length=255)),
                ('payment_types', models.JSONField(blank=True, default=dict, null=True)),
                ('extra_prices', models.JSONField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='school_logos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('reschedule_time_limit', models.PositiveIntegerField(default=24)),
                ('schedule_time_limit', models.PositiveIntegerField(default=24)),
                ('currency', models.CharField(default='EUR', max_length=20)),
                ('notification_templates', models.JSONField(blank=True, default=schools.models.default_notification_templates, help_text='Customizable templates for notifications.')),
                ('alerts', models.JSONField(blank=True, default=schools.models.default_alerts)),
            ],
        ),
    ]
