# Generated by Django 5.1.6 on 2025-02-27 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('schools', '0001_initial'),
        ('sports', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='school_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='schools', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='school',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='schools', to='locations.location'),
        ),
        migrations.AddField(
            model_name='school',
            name='monitors',
            field=models.ManyToManyField(blank=True, related_name='schools', to='users.monitor'),
        ),
        migrations.AddField(
            model_name='school',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='schools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='schools', to='sports.sport'),
        ),
        migrations.AddField(
            model_name='school',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='schools', to='users.student'),
        ),
        migrations.AddField(
            model_name='review',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='schools.school'),
        ),
    ]
