# Generated by Django 5.1.6 on 2025-02-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='pack_prices',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
