# Generated by Django 5.1.5 on 2025-04-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='contacts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
