# Generated by Django 5.1.5 on 2025-02-19 10:57

import schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='payment_types',
            field=models.JSONField(blank=True, default=schools.models.default_payment_types, null=True),
        ),
    ]
