# Generated by Django 5.1.5 on 2025-02-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_school_payment_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='attendance_by_date',
        ),
        migrations.AddField(
            model_name='school',
            name='scheduled_and_rescheduled_dict',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
