# Generated by Django 5.1.5 on 2025-04-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_contacts'),
        ('users', '0004_instructor_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='users.instructor'),
        ),
    ]
