# Generated by Django 5.1.6 on 2025-02-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_school_pack_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='payment_types',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
