# Generated by Django 5.1.5 on 2025-01-23 12:57

import schools.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('schools', '0004_alter_school_group_lessons_pack_prices_and_more'),
        ('users', '0003_discount_school_studentgroup_school_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='equipment_prices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='extras_prices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='group_lessons_pack_prices',
            field=models.JSONField(blank=True, default=schools.models.default_group_lessons_pack_prices),
        ),
        migrations.AlterField(
            model_name='school',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='schools', to='users.instructor'),
        ),
        migrations.AlterField(
            model_name='school',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='schools', to='locations.location'),
        ),
        migrations.AlterField(
            model_name='school',
            name='monitors',
            field=models.ManyToManyField(blank=True, related_name='schools', to='users.monitor'),
        ),
        migrations.AlterField(
            model_name='school',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='schools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='school',
            name='payment_types',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='private_lessons_pack_prices',
            field=models.JSONField(blank=True, default=schools.models.default_private_lessons_pack_prices),
        ),
        migrations.AlterField(
            model_name='school',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='schools', to='users.student'),
        ),
    ]
