# Generated by Django 5.1.5 on 2025-02-22 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_remove_school_attendance_by_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='scheduled_and_rescheduled_dict',
        ),
    ]
