# Generated by Django 5.1.6 on 2025-02-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_school_payment_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='services',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
