# Generated by Django 5.1.5 on 2025-01-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_school_attendance_by_date'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='schools', to='sports.sport'),
        ),
    ]
