# Generated by Django 5.1.5 on 2025-01-27 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_school_notification_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='reschedule_time_limit',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
