# Generated by Django 5.1.5 on 2025-01-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_school_reschedule_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='schedule_time_limit',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
