# Generated by Django 5.1.5 on 2025-02-03 12:49

import schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_school_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='notification_templates',
            field=models.JSONField(blank=True, default=schools.models.default_notification_templates, help_text='Customizable templates for notifications.'),
        ),
    ]
