# Generated by Django 5.1.5 on 2025-01-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroupClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration_in_minutes', models.PositiveIntegerField()),
                ('level', models.PositiveIntegerField()),
                ('minimum_age', models.PositiveIntegerField()),
                ('maximum_age', models.PositiveIntegerField()),
                ('maximum_number_of_students', models.PositiveIntegerField()),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroupPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_of_classes', models.PositiveIntegerField()),
                ('number_of_classes_left', models.PositiveIntegerField()),
                ('duration_in_minutes', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_done', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('finished_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration_in_minutes', models.PositiveIntegerField()),
                ('class_number', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_done', models.BooleanField(default=False)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivatePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_of_classes', models.PositiveIntegerField()),
                ('duration_in_minutes', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_done', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('finished_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
            ],
        ),
    ]
