# Generated by Django 5.1.5 on 2025-01-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupclass',
            old_name='time',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='privateclass',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='groupclass',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
