# Generated by Django 5.1.5 on 2025-01-23 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_groupclass_type_privateclass_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatepack',
            name='parents',
        ),
        migrations.AddField(
            model_name='privatepack',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='private_packs', to=settings.AUTH_USER_MODEL),
        ),
    ]
