# Generated by Django 5.1.5 on 2025-01-24 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_remove_privatepack_parents_privatepack_parents'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateclass',
            name='feedback',
        ),
        migrations.AddField(
            model_name='classticket',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_tickets', to='sports.sport'),
        ),
        migrations.AddField(
            model_name='groupclass',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_classes', to='sports.sport'),
        ),
        migrations.AddField(
            model_name='grouppack',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_packs', to='sports.sport'),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_classes', to='sports.sport'),
        ),
        migrations.AddField(
            model_name='privatepack',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_packs', to='sports.sport'),
        ),
    ]
