# Generated by Django 5.1.5 on 2025-01-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_remove_privateclass_feedback_classticket_sport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatepack',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
