# Generated by Django 5.1.5 on 2025-01-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0015_alter_privatepack_expiration_date'),
        ('users', '0004_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateclass',
            name='number_of_extra_students',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='extra_students',
            field=models.ManyToManyField(blank=True, related_name='extra_private_classes', to='users.student'),
        ),
    ]
