# Generated by Django 5.1.5 on 2025-02-05 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0017_remove_privateclass_students_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppack',
            name='parents',
        ),
        migrations.AddField(
            model_name='grouppack',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='group_packs', to=settings.AUTH_USER_MODEL),
        ),
    ]
