# Generated by Django 5.1.5 on 2025-01-22 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0002_initial'),
        ('progress', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='users.student'),
        ),
        migrations.AddField(
            model_name='instructorfeedback',
            name='group_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_feedback', to='lessons.groupclass'),
        ),
        migrations.AddField(
            model_name='instructorfeedback',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='instructorfeedback',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_feedback', to='lessons.privateclass'),
        ),
        migrations.AddField(
            model_name='instructorfeedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='users.student'),
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='group_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='lessons.groupclass'),
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='lessons.privateclass'),
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='users.student'),
        ),
        migrations.AddField(
            model_name='progressreport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='users.student'),
        ),
        migrations.AddField(
            model_name='progressrecord',
            name='covered_skills',
            field=models.ManyToManyField(blank=True, related_name='progress_records', to='progress.skill'),
        ),
        migrations.AddField(
            model_name='goal',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='progress.skill'),
        ),
        migrations.AddField(
            model_name='skillproficiency',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proficiencies', to='progress.skill'),
        ),
        migrations.AddField(
            model_name='skillproficiency',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_proficiencies', to='users.student'),
        ),
    ]
