# Generated by Django 5.1.5 on 2025-01-24 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_initial'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='sports.sport'),
        ),
    ]
