# Generated by Django 5.1.6 on 2025-02-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(default='Notification from MyLessons', max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('date_read', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('activities', models.ManyToManyField(blank=True, related_name='notifications', to='events.activity')),
                ('lessons', models.ManyToManyField(blank=True, related_name='notifications', to='lessons.lesson')),
                ('packs', models.ManyToManyField(blank=True, related_name='notifications', to='lessons.pack')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
