# Generated by Django 5.1.5 on 2025-01-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_starting_time_activity_start_time_and_more'),
        ('lessons', '0014_remove_privateclass_feedback_classticket_sport_and_more'),
        ('notifications', '0003_notification_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-sent_at']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='time',
        ),
        migrations.AddField(
            model_name='notification',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='events.activity'),
        ),
        migrations.AddField(
            model_name='notification',
            name='date_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='group_classes',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='lessons.groupclass'),
        ),
        migrations.AddField(
            model_name='notification',
            name='group_packs',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='lessons.grouppack'),
        ),
        migrations.AddField(
            model_name='notification',
            name='private_classes',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='lessons.privateclass'),
        ),
        migrations.AddField(
            model_name='notification',
            name='private_packs',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='lessons.privatepack'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
