# Generated by Django 5.1.5 on 2025-02-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_groupclass_instructors_and_more'),
        ('notifications', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='group_classes',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='group_packs',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='private_classes',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='private_packs',
        ),
        migrations.AddField(
            model_name='notification',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='notification',
            name='packs',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='lessons.pack'),
        ),
    ]
