# Generated by Django 5.1.5 on 2025-01-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_options_remove_notification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(default='Notification from MyLessons', max_length=255),
        ),
    ]
