# Generated by Django 5.1.5 on 2025-01-22 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('events', '0001_initial'),
        ('locations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='instructors',
            field=models.ManyToManyField(related_name='activities', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='activity',
            name='monitors',
            field=models.ManyToManyField(related_name='activities', to='users.useraccount'),
        ),
        migrations.AddField(
            model_name='activity',
            name='students',
            field=models.ManyToManyField(related_name='activities', to='users.student'),
        ),
        migrations.AddField(
            model_name='activitymodel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='locations.location'),
        ),
        migrations.AddField(
            model_name='birthdayparty',
            name='activities',
            field=models.ManyToManyField(related_name='birthday_parties', to='events.activity'),
        ),
        migrations.AddField(
            model_name='birthdayparty',
            name='equipment',
            field=models.ManyToManyField(related_name='birthday_parties', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='birthdayparty',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_parties', to='users.student'),
        ),
        migrations.AddField(
            model_name='camp',
            name='activities',
            field=models.ManyToManyField(related_name='camps', to='events.activity'),
        ),
        migrations.AddField(
            model_name='camporder',
            name='activities',
            field=models.ManyToManyField(related_name='camp_orders', to='events.activity'),
        ),
        migrations.AddField(
            model_name='camporder',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_orders', to='users.student'),
        ),
        migrations.AddField(
            model_name='camporder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_orders', to='users.useraccount'),
        ),
    ]
