# Generated by Django 5.1.5 on 2025-01-22 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='schools.school'),
        ),
        migrations.AddField(
            model_name='activitymodel',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_models', to='schools.school'),
        ),
        migrations.AddField(
            model_name='camp',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camps', to='schools.school'),
        ),
        migrations.AddField(
            model_name='camporder',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camp_orders', to='schools.school'),
        ),
    ]
