# Generated by Django 5.1.5 on 2025-01-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_activity_activity_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
