# Generated by Django 5.1.6 on 2025-02-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_in_minutes', models.PositiveIntegerField()),
                ('class_number', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('extras', models.JSONField(blank=True, default=dict, null=True)),
                ('level', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_age', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_age', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_number_of_students', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(default='private', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(default='private', max_length=255)),
                ('number_of_classes', models.PositiveIntegerField()),
                ('number_of_classes_left', models.PositiveIntegerField()),
                ('duration_in_minutes', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_done', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('finished_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
            ],
        ),
    ]
