# Generated by Django 5.1.5 on 2025-02-17 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_initial'),
        ('lessons', '0001_initial'),
        ('locations', '0001_initial'),
        ('schools', '0001_initial'),
        ('sports', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classticket',
            name='extra_students',
            field=models.ManyToManyField(blank=True, related_name='extra_class_tickets', to='users.student'),
        ),
        migrations.AddField(
            model_name='classticket',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_tickets', to='schools.school'),
        ),
        migrations.AddField(
            model_name='classticket',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_tickets', to='sports.sport'),
        ),
        migrations.AddField(
            model_name='classticket',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_tickets', to='users.student'),
        ),
        migrations.AddField(
            model_name='groupclass',
            name='instructors',
            field=models.ManyToManyField(related_name='group_classes', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='groupclass',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_classes', to='locations.location'),
        ),
        migrations.AddField(
            model_name='groupclass',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_classes', to='schools.school'),
        ),
        migrations.AddField(
            model_name='groupclass',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_classes', to='sports.sport'),
        ),
        migrations.AddField(
            model_name='groupclass',
            name='students',
            field=models.ManyToManyField(related_name='group_classes', to='users.student'),
        ),
        migrations.AddField(
            model_name='classticket',
            name='group_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_tickets', to='lessons.groupclass'),
        ),
        migrations.AddField(
            model_name='grouppack',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='group_packs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouppack',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_packs', to='schools.school'),
        ),
        migrations.AddField(
            model_name='grouppack',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_packs', to='sports.sport'),
        ),
        migrations.AddField(
            model_name='grouppack',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_packs', to='users.student'),
        ),
        migrations.AddField(
            model_name='classticket',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='lessons.grouppack'),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='equipments',
            field=models.ManyToManyField(blank=True, related_name='private_classes', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='extra_students',
            field=models.ManyToManyField(blank=True, related_name='extra_private_classes', to='users.student'),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_private_classes', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_classes', to='locations.location'),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_classes', to='schools.school'),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_classes', to='sports.sport'),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='students',
            field=models.ManyToManyField(related_name='private_classes', to='users.student'),
        ),
        migrations.AddField(
            model_name='privatepack',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_packs', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='privatepack',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='private_packs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatepack',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_packs', to='schools.school'),
        ),
        migrations.AddField(
            model_name='privatepack',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_packs', to='sports.sport'),
        ),
        migrations.AddField(
            model_name='privatepack',
            name='students',
            field=models.ManyToManyField(related_name='private_packs', to='users.student'),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='lessons.privatepack'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='group_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='lessons.grouppack'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='private_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='lessons.privatepack'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='schools.school'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
