# Generated by Django 5.1.6 on 2025-02-27 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('locations', '0001_initial'),
        ('schools', '0001_initial'),
        ('sports', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='locations.location'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schools.school'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='sports.sport'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='students',
            field=models.ManyToManyField(related_name='lessons', to='users.student'),
        ),
        migrations.AddField(
            model_name='pack',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='packs', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='pack',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='packs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pack',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='schools.school'),
        ),
        migrations.AddField(
            model_name='pack',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packs', to='sports.sport'),
        ),
        migrations.AddField(
            model_name='pack',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='packs', to='users.student'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.pack'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='vouchers', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='packs',
            field=models.ManyToManyField(blank=True, related_name='vouchers', to='lessons.pack'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='schools.school'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
