# Generated by Django 5.1.5 on 2025-02-20 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_initial'),
        ('locations', '0001_initial'),
        ('schools', '0003_alter_school_payment_types'),
        ('sports', '0001_initial'),
        ('users', '0004_useraccount_payment_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupclass',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='groupclass',
            name='location',
        ),
        migrations.RemoveField(
            model_name='groupclass',
            name='school',
        ),
        migrations.RemoveField(
            model_name='groupclass',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='groupclass',
            name='students',
        ),
        migrations.RemoveField(
            model_name='grouppack',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='grouppack',
            name='school',
        ),
        migrations.RemoveField(
            model_name='grouppack',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='grouppack',
            name='student',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='group_pack',
        ),
        migrations.RemoveField(
            model_name='privateclass',
            name='equipments',
        ),
        migrations.RemoveField(
            model_name='privateclass',
            name='extra_students',
        ),
        migrations.RemoveField(
            model_name='privateclass',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='privateclass',
            name='location',
        ),
        migrations.RemoveField(
            model_name='privateclass',
            name='pack',
        ),
        migrations.RemoveField(
            model_name='privateclass',
            name='school',
        ),
        migrations.RemoveField(
            model_name='privateclass',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='privateclass',
            name='students',
        ),
        migrations.RemoveField(
            model_name='privatepack',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='privatepack',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='privatepack',
            name='school',
        ),
        migrations.RemoveField(
            model_name='privatepack',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='privatepack',
            name='students',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='private_pack',
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration_in_minutes', models.PositiveIntegerField()),
                ('class_number', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_done', models.BooleanField(default=False)),
                ('extras', models.JSONField(blank=True, default=dict, null=True)),
                ('level', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_age', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_age', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_number_of_students', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(default='private', max_length=50)),
                ('instructors', models.ManyToManyField(blank=True, related_name='lessons', to='users.instructor')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='locations.location')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schools.school')),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='sports.sport')),
                ('students', models.ManyToManyField(related_name='lessons', to='users.student')),
            ],
        ),
        migrations.AddField(
            model_name='voucher',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='vouchers', to='lessons.lesson'),
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(default='private', max_length=255)),
                ('number_of_classes', models.PositiveIntegerField()),
                ('number_of_classes_left', models.PositiveIntegerField()),
                ('duration_in_minutes', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_done', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('finished_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('instructors', models.ManyToManyField(blank=True, related_name='packs', to='users.instructor')),
                ('parents', models.ManyToManyField(blank=True, related_name='packs', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='schools.school')),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packs', to='sports.sport')),
                ('students', models.ManyToManyField(blank=True, related_name='packs', to='users.student')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.pack'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='packs',
            field=models.ManyToManyField(blank=True, related_name='vouchers', to='lessons.pack'),
        ),
        migrations.DeleteModel(
            name='ClassTicket',
        ),
    ]
