# Generated by Django 5.1.5 on 2025-03-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='packs',
            field=models.ManyToManyField(blank=True, related_name='lessons_many', to='lessons.pack'),
        ),
    ]
