# Generated by Django 5.1.5 on 2025-02-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_groupclass_instructors_and_more'),
        ('notifications', '0004_remove_notification_group_classes_and_more'),
        ('payments', '0003_rename_birthday_party_payment_birthday_parties_and_more'),
        ('progress', '0003_remove_progressrecord_group_class_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupClass',
        ),
        migrations.DeleteModel(
            name='GroupPack',
        ),
        migrations.DeleteModel(
            name='PrivateClass',
        ),
        migrations.DeleteModel(
            name='PrivatePack',
        ),
    ]
