# Generated by Django 5.1.5 on 2025-01-22 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_rename_time_groupclass_start_time_and_more'),
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classticket',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_tickets', to='schools.school'),
        ),
        migrations.AddField(
            model_name='groupclass',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_classes', to='schools.school'),
        ),
        migrations.AddField(
            model_name='grouppack',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_packs', to='schools.school'),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_classes', to='schools.school'),
        ),
        migrations.AddField(
            model_name='privatepack',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_packs', to='schools.school'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='schools.school'),
        ),
    ]
