# Generated by Django 5.1.5 on 2025-01-22 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_classticket_school_groupclass_school_and_more'),
        ('users', '0003_discount_school_studentgroup_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatepack',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_packs', to='users.instructor'),
        ),
    ]
