# Generated by Django 5.1.5 on 2025-02-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_delete_groupclass_delete_grouppack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
