# Generated by Django 5.1.5 on 2025-05-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_monitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='calendar_event_ids',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
