# Generated by Django 5.1.5 on 2025-05-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lesson_calendar_event_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='last_calendar_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='needs_calendar_sync',
            field=models.BooleanField(default=False),
        ),
    ]
