# Generated by Django 5.1.5 on 2025-01-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_privatepack_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppack',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='group_packs', to='lessons.classticket'),
        ),
    ]
