# Generated by Django 5.1.5 on 2025-05-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lesson_last_calendar_sync_lesson_needs_calendar_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='needs_calendar_sync',
            field=models.BooleanField(default=True),
        ),
    ]
