# Generated by Django 5.1.5 on 2025-01-23 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_grouppack_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classticket',
            name='group_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_tickets', to='lessons.groupclass'),
        ),
    ]
