# Generated by Django 5.1.5 on 2025-06-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_lesson_needs_calendar_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='old_id_str',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='old_id_str',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
