# Generated by Django 5.1.5 on 2025-01-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_classticket_group_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupclass',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
