# Generated by Django 5.1.5 on 2025-01-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_groupclass_end_time_alter_privateclass_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupclass',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupclass',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
