# Generated by Django 5.1.5 on 2025-01-23 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_alter_groupclass_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppack',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='privatepack',
            name='classes',
        ),
        migrations.AddField(
            model_name='classticket',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='lessons.grouppack'),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='lessons.privatepack'),
        ),
    ]
