# Generated by Django 5.1.5 on 2025-01-23 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_remove_grouppack_tickets_remove_privatepack_classes_and_more'),
        ('users', '0003_discount_school_studentgroup_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateclass',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_private_classes', to='users.instructor'),
        ),
    ]
