# Generated by Django 5.1.5 on 2025-01-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_alter_privateclass_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupclass',
            name='type',
            field=models.CharField(default='group_lesson', max_length=50),
        ),
        migrations.AddField(
            model_name='privateclass',
            name='type',
            field=models.CharField(default='private_lesson', max_length=50),
        ),
    ]
