# Generated by Django 5.1.5 on 2025-01-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_privateclass_number_of_extra_students_and_more'),
        ('users', '0004_alter_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateclass',
            name='students',
        ),
        migrations.RemoveField(
            model_name='privatepack',
            name='students',
        ),
        migrations.AddField(
            model_name='privateclass',
            name='students',
            field=models.ManyToManyField(related_name='private_classes', to='users.student'),
        ),
        migrations.AddField(
            model_name='privatepack',
            name='students',
            field=models.ManyToManyField(related_name='private_packs', to='users.student'),
        ),
    ]
