# Generated by Django 5.1.5 on 2025-02-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0018_remove_grouppack_parents_grouppack_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupclass',
            name='type',
            field=models.CharField(default='Group', max_length=50),
        ),
        migrations.AlterField(
            model_name='privateclass',
            name='type',
            field=models.CharField(default='Private', max_length=50),
        ),
    ]
