# Generated by Django 5.1.5 on 2025-02-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0019_alter_groupclass_type_alter_privateclass_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='classticket',
            name='ticket_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
