# Generated by Django 5.1.5 on 2025-02-14 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0020_classticket_ticket_number'),
        ('locations', '0005_location_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupclass',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_classes', to='locations.location'),
        ),
    ]
