# Generated by Django 5.1.5 on 2025-02-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0021_alter_groupclass_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateclass',
            name='expiration_date',
        ),
    ]
