# Generated by Django 5.1.5 on 2025-02-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0022_remove_privateclass_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppack',
            name='type',
            field=models.CharField(default='Group', max_length=50),
        ),
        migrations.AddField(
            model_name='privatepack',
            name='type',
            field=models.CharField(default='Private', max_length=50),
        ),
    ]
