name: CI/CD Django + Flutter

# 1) Top-level IMAGE_NAME is fine — GH will interpolate this once, early
env:
  IMAGE_NAME: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lowercase IMAGE_NAME
        run: |
          IMAGE_NAME=$(echo "${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    # only define real secrets & contexts here — do NOT try to re-use env.IMAGE_NAME
    env:
      VM_IP:    ${{ secrets.VM_IP }}
      VM_PORT:  ${{ secrets.VM_PORT }}
      VM_USER:  ${{ secrets.VM_USER }}
      GHCR_USER: ${{ github.actor }}
      GHCR_PAT:  ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      - name: Deploy to Production
        run: |
          ssh -o StrictHostKeyChecking=no \
              -p "$VM_PORT" \
              "$VM_USER@$VM_IP" << EOF
            set -e
            cd /opt/mylessons

            # (optional) keep your host repo in sync
            git remote set-url origin https://${GHCR_USER}:${GHCR_PAT}@github.com/${GHCR_USER}/MyLessons-Project.git
            git fetch --depth=1 origin main
            git reset --hard FETCH_HEAD

            # login & clean up old cruft
            echo "$GHCR_PAT" | docker login ghcr.io -u "$GHCR_USER" --password-stdin
            docker container prune -f
            docker image prune -af

            # pull & deploy the new build (no local build, no dangling layers)
            docker pull ${{ env.IMAGE_NAME }}:latest
            docker compose up -d --remove-orphans --no-build
            docker compose logs --tail=50
          EOF
