name: CI/CD Django + Flutter


# ─── Grant the token permission to push to GHCR ───────────────────────────────
permissions:
  contents: read     # (you usually only need to read the repo)
  packages: write    # ← this unlocks docker push to ghcr.io


on:
  push:
    branches:
      - main       # deploy para produção
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lowercase IMAGE_NAME
        run: |
          echo "IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH & Docker Compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_IP }}
          port: ${{ secrets.VM_PORT }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_PASSWORD }}
          script: |
            cd /opt/mylessons
            docker-compose pull
            docker-compose up -d
            docker-compose logs --tail=50
